{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cilium-egress-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cilium-egress-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cilium-egress-operator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 8080
          protocol: TCP
        - port: 8081
          protocol: TCP
  egress:
    - ports:
        - port: 443
          protocol: TCP
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
{{- end }}
