apiVersion: v1
kind: ServiceAccount
metadata:
  name: cilium-egress-operator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cilium-egress-operator
rules:
  - apiGroups: ["egress.cilium.io"]
    resources: ["egressgateways", "egressgateways/status"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cilium-egress-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cilium-egress-operator
subjects:
  - kind: ServiceAccount
    name: cilium-egress-operator
    namespace: kube-system
